import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Lessons from '../components/lessons'
import Users from '../components/users'
import styles from '../styles/Home.module.css'
// import ExelData from '../components/exelData';
import SendData from '../components/sendData'
import ComputerGroupSourceInformation from '../components/computerGroupSourceInformation';
import LessonsUsers from '../components/lessonsUsers';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const Home: NextPage = () => {
  return (
    <div className={`${styles.container} ${styles['dir-rtl']}`}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='text-center py-5 border-b-[1px] border-[#c2c2c2]'>برنامه مدیریت دروس</div>
      <div className='my-5 border-b-[1px] border-[#c2c2c2]'>
        <ComputerGroupSourceInformation />
      </div>
      <div className='my-5 border-b-[1px] border-[#c2c2c2]'>
        <Lessons />
      </div>
      <div className='my-5 border-b-[1px] border-[#c2c2c2]'>
        <LessonsUsers />
      </div>
      <div className='my-5 border-b-[1px] border-[#c2c2c2]'>
        <Users />
      </div>
      <div className='my-5 border-b-[1px] border-[#c2c2c2]'>
        <SendData />
      </div>
      {/* <div className='my-5 border-b-[1px] border-[#c2c2c2]'>
        <ExelData/>
      </div> */}
      <footer className={`${styles.footer} ${styles['dir-ltr']} `}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
      <ToastContainer
                position="top-right"
                autoClose={5000}
                hideProgressBar={false}
                newestOnTop={false}
                closeOnClick
                rtl={false}
                pauseOnFocusLoss
                draggable
                pauseOnHover
            />
    </div>
  )
}

export default Home
